repo: src
patches:
-
  author: null
  file: Add-support-for-using-seccomp_bpf-on-mips64el.patch
  description: null
-
  author: null
  file: Set-kernal-page-size-to-16K-on-loongson-MIPS-archtec.patch
  description: null
-
  author: null
  file: Add-mips64el-redhat-linux-to-gcc_toolchain-for-mips6.patch
  description: null
-
  author: null
  file: Fix-mips-cross-toolchain-build-src-crypto-ec-p256-64.patch
  description: null
-
  author: null
  file: Fix-error-about-relocation-truncated-to-fit-R_MIPS_C.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: backport-sqlite-8a87f7e.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: backport-sqlite-9851f2e.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: backport-sqlite-3d8ec48.patch
  description: null
-
  author: Cheng Zhao <zcbenz@gmail.com>
  file: support-old-nss.patch
  description: null
